### PR TITLE
feat(app/ui): reuse code from @influxdata/influxdb-client-giraffe

### PR DESCRIPTION
**Pull request by sranka**
This PR upgrades the code to reuse code from `@influxdata/influxdb-client-giraffe` + upgrades @influxdata/influxdb-client to version 1.9.0 .

- [x] Rebased/mergeable
- [x] A test has been added if appropriate
- [x] Tests run successfully
- [x] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)

### CODE REVIEW

**Review by bednar — COMMENTED** [review]
There is a `TypeError` on DeviceRegistration:

image

I tried it via `docker-compose up` on fresh containers.

**Comment by sranka** [comment]
Thank you @bednar ... this defect existed before this PR, I fixed it herein as well

**Comment by sranka** [comment]
@Sciator FYI, these are likely yours leftovers: 3d88de5893e5a076d60527802678cac41988c595 e4ab30ab6ec760036e0789ef15d80c41720293ef as well as 
```
[1] Compiled with warnings.
[1] 
[1] ./src/pages/DashboardPage.tsx
[1]   Line 185:6:   React Hook useEffect has a missing dependency: 'measurementsDefinitions'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
[1]   Line 189:6:   React Hook useEffect has a missing dependency: 'resetXDomain'. Either include it or remove the dependency array             react-hooks/exhaustive-deps
[1]   Line 363:13:  Arrow function expected a return value                                                                                      array-callback-return
```

**Review by bednar — APPROVED** [review]
From my POV awesome as usually 🍺

**Pull request merged**
